// <auto-generated />
namespace RashahlyKtab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MoveCurrentEventfromContributortoContribution : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoveCurrentEventfromContributortoContribution));
        
        string IMigrationMetadata.Id
        {
            get { return "201411110716271_Move CurrentEvent from Contributor to Contribution"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
