// <auto-generated />
namespace RashahlyKtab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class After_merge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(After_merge));
        
        string IMigrationMetadata.Id
        {
            get { return "201411011124504_After_merge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
